### ISSUE TITLE
gui not showing up on second launch

### ISSUE THREAD

**Issue by PonyJohnny** [SlimeVR/SlimeVR-GUI#11]
slimevr-ui.exe does not show up after the first launch, just runs the process and that's it.
I managed to run it again by deleteding the slimevr.dev folder in %appdata% but cannot track the root of the issue

I have multi-monitor setup but this seem not to be the issue.

It's kind of a bummer because i thought it does not work at all on my machine.
The first time I ran the .exe file, I did not have the slimevr server running, so on the following attempts slimevr-ui.exe would close immediately after clicking on the .exe, possibly due to a faulty config file or something.
In this situation, it was even difficult to even track the running process in the task manager.

However the issue still persists even after completing the trackers setup.

**Comment by loucass003** [comment]
I am pretty sure i fixed this already what exe file did you grab?

**Comment by loucass003** [comment]
There should be a more recent one with the fix on it. I didn't make a release for it yet

**Comment by PonyJohnny** [comment]
actually I tried both, 0.2.1 and 0.1.0 on two different machines

**Comment by loucass003** [comment]
The 0.1.0 wont work anymore.
The 0.2.1 has the issue you are speaking about.
I sent a fix for it on the discord. But didn't make a release yet

**Comment by PonyJohnny** [comment]
Sorry, couldn't find anything about this topic on the server and thought it was an individual thing
Will wait for the release here, thank you

**Comment by loucass003** [comment]
You can @loucass003 on discord. Ill give you the link to the right one. I dont want to do a new release yet
