### ISSUE TITLE
Shake highlight does not work in dev mode

### ISSUE THREAD

**Issue by nullstalgia** [SlimeVR/SlimeVR-GUI#25]
I'm not sure if this is intentional, but when using the dev mode to see rotations in the new UI, shaking the tracker does not cause the highlight ring to appear.

**Comment by loucass003** [comment]
this is not a bug. It is just not implemented.

i though having the rotation numbers moving was enough

**Comment by nullstalgia** [comment]
When it comes to identifying trackers, a light changing brightness is still more intuitive for devs as well as users. 😅 Especially if a user turns on the mode to see the extra information but doesn't want to make full use of it.

Just a QOL thing, not super high priority!
