### ISSUE TITLE
Release v0.1.0 virus warning

### ISSUE THREAD

**Issue by figinternet** [SlimeVR/SlimeVR-GUI#9]
On Windows 10 (Build 10.0.19044.1826) on multiply computers Windows defender will fire a virus warning that Trojan:Win32/Phonzy.A!ml is found

I think this is a false-positive, 

Does someone else has the same issues ?

**Comment by Kamilake** [comment]
I'm using `Windows Defender 1.373.129.0` on `Windows 10 21H1 (19042)` but I haven't found any positive in all releases.   
It's been modified in a few days, or it's probably due to heuristic detection, so I think we'll have to wait a little longer to find out.

**Comment by deiteris** [comment]
It's possible to report false positive on this page:
https://www.microsoft.com/en-us/wdsi/filesubmission/
